# Cloud Build for GitHub connection (repo: goog-ac/cv_review)
# Builds backend and frontend from Dockerfiles, pushes to Artifact Registry, deploys to Cloud Run (europe-west1).
# Substitute _PROJECT_ID and _REGION when creating the trigger.
substitutions:
  _PROJECT_ID: your-gcp-project-id
  _REGION: europe-west1
  _SERVICE_NAME: goog-demo-cv0
  _REPO_NAME: cv_review

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Backend: build from backend/ using backend/Dockerfile
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend:latest
      - -f
      - backend/Dockerfile
      - backend
    dir: .

  - id: push-backend
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}
    waitFor: [build-backend]

  - id: push-backend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend:latest
    waitFor: [build-backend]

  # Deploy backend to Cloud Run (goog-demo-cv0)
  - id: deploy-backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
    waitFor: [push-backend]

  # Frontend: build from frontend/ using frontend/Dockerfile
  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/frontend:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/frontend:latest
      - -f
      - frontend/Dockerfile
      - frontend
    dir: .

  - id: push-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/frontend:${SHORT_SHA}
    waitFor: [build-frontend]

  - id: deploy-frontend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - goog-demo-cv0-frontend
      - --image
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/frontend:${SHORT_SHA}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
    waitFor: [push-frontend]

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend:latest
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/frontend:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/frontend:latest
