# Cloud Run service: goog-demo-cv0-frontend (optional)
# Region: europe-west1
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: goog-demo-cv0-frontend
  labels:
    cloud.googleapis.com/location: europe-west1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
      - image: europe-west1-docker.pkg.dev/PROJECT_ID/cv_review/frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
  traffic:
  - percent: 100
    latestRevision: true
